language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build
branches:
  only:
  - dev
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "Travis CI"
- git config user.email eagleeyes91@gmail.com
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_TOKEN}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/eagleeye/eagleeye.github.io.git
  - REPO_TARGET_BRANCH: master
  - secure: Vlj2MZ9ikf4cu58aRfWfz6Y9JaqEMDjAEKkKy+NB979/7aBLmKiKwhQSbCZe+SVijFXMg5TEszk0mvrOLQJNQYFGdw/34whJ3Va880D43XhNDS9/OqTfPaNwpOgSlLuqf78t6kLziilHk7qSTg9YxVyR5/PY1T/XNXQOc7UMlvc=
