language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build
branches:
  only:
  - dev
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "Travis CI"
- git config user.email eagleeyes91@gmail.com
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_TOKEN}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/eagleeye/eagleeye.github.io.git
  - REPO_TARGET_BRANCH: master
  - secure: dypbo1wKSFsOHB3YQnalRn0VPM0pWDnFv4LebLjjNCog0Lnf0pehKiJHus29Q6/0ef9JHjPbk56PxjLJtAAIrnvwiZy7zFqhPIw5iRA3Rh3dyIRLroX5s336hUqiEk9cB5UWKmNoBcVCi0JsOqOzNo9wO+YWtwYCUpxb40dF2dI=
